## Scipy
> high-level scientific computing

In [318]:
import numpy as np # import numpy
import scipy # import scipy

# it is built on top of NumPy

### file input/output (scipy.io)

In [319]:
from scipy import io # import i/o module

In [320]:
a = np.ones((3, 3)) # 3x3 array of ones
io.savemat('file.mat', {'a': a}) # {'a': a} means variable name 'a' stored in file
# savemat() expects a dictionary

In [321]:
data = io.loadmat('file.mat') # returns dictionary
data['a']

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### special functions (scipy.special)

In [322]:
from scipy import special # import special functions module

In [323]:
special.erf(0) # erf() --> error function
# used in probability and gaussian distributions

0.0

### linear algebra (scipy.linalg)

In [324]:
from scipy import linalg # import linear algebra module

#### determinant

In [325]:
arr = np.array([[1, 2], [3, 4]])

linalg.det(arr) # det() --> determinant of square matrix
# tells if matrix is invertible (det != 0)

-2.0

#### inverse

In [326]:
linalg.inv(arr) # inv() --> matrix inverse
# only works if matrix is non-singular

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### singular value decomposition (SVD)

In [327]:
arr = np.arange(9).reshape((3, 3))
U, s, Vh = linalg.svd(arr) # svd() --> decomposes matrix into U, Σ, Vh
# used in dimensionality reduction and signal processing

### interpolation (scipy.interpolate)
to estimate unknown values between data points

In [328]:
from scipy.interpolate import interp1d # import interpolation module

In [329]:
# sample data
measured_time = np.linspace(0, 1, 10)
noise = np.random.normal(0, 0.1, 10)
measures = np.sin(2 * np.pi * measured_time) + noise

In [330]:
# build interpolation function
linear_interp = interp1d(measured_time, measures)
# default --> linear interpolation

In [331]:
# evaluate new points
interpolation_time = np.linspace(0, 1, 50)
linear_results = linear_interp(interpolation_time)
# gives estimated values at new time points

In [332]:
# cubic interpolation
cubic_interp = interp1d(measured_time, measures, kind = 'cubic') # kind = 'cubic' --> smoother curve

### optimization and fit (scipy.optimize)
for minimizing functions, fitting curves, finding roots

In [333]:
from scipy import optimize # import optimization module

#### curve fitting

In [334]:
def test_func(x, a, b):
    return a * np.sin(b * x)

In [335]:
# sample data
x_data = np.linspace(-5, 5, num = 50) # 50 evenly spaced points
y_data = 2.9 * np.sin(1.5 * x_data) # sine curve
y_data = y_data + np.random.normal(size = 50) # add noise

params, params_covariance = optimize.curve_fit(test_func, x_data, y_data) # curve_fit() --> finds best values of a and b
# returns optimized parameters and covariance matrix

#### minimization

In [336]:
def f(x):
    return x**2 + 10*np.sin(x)

In [337]:
result = optimize.minimize(f, x0 = 0) # minimize() --> finds local minimum, x0 --> initial guess
result.x # result.x --> location of minimum

array([-1.30644012])

#### finding roots

In [338]:
root = optimize.root(f, x0 = 1) # root() --> finds x where f(x) = 0, x0 --> initial guess
root.x

array([0.])

### statistics and random numbers (scipy.stats)
statistical tools and probability distributions

In [339]:
from scipy import stats # import stats module

#### histogram and pdf

In [340]:
samples = np.random.normal(size = 1000)
bins = np.arange(-4, 5)

hist, bins = np.histogram(samples, bins = bins, density = True)
# histogram --> estimate probability density
# density = True --> normalizes area to 1

In [341]:
# normal distribution object
dist = stats.norm() # normal distribution object
pdf = dist.pdf(bins) # probability density function

#### mean and median

In [342]:
np.mean(samples) # average
np.median(samples) # middle value (robust to outliers)

0.03862664471535519

In [343]:
# percentiles
stats.scoreatpercentile(samples, 50) # 50th percentile (median)
stats.scoreatpercentile(samples, 90) # 90th percentile

1.3179806111074708

#### statistical test (t-test)

In [344]:
a = np.random.normal(0, 1, size = 100)
b = np.random.normal(1, 1, size = 100)

stats.ttest_ind(a, b)
# ttest_ind() --> compares means of two independent samples
# returns t-statistic and p-value

Ttest_indResult(statistic=-7.321549732664383, pvalue=6.022307208569682e-12)

### numerical integration (scipy.integrate)
for computing integrals and solving oeds

In [345]:
from scipy.integrate import quad
res, err = quad(np.sin, 0, np.pi/2) # quad() --> computes definite integral
# returns result and estimated error

#### oed solving

In [346]:
from scipy.integrate import odeint

In [347]:
def calc_derivative(ypos, time):
    return -2 * ypos

In [348]:
time_vec = np.linspace(0, 4, 40)
y = odeint(calc_derivative, y0 = 1, t = time_vec) # odeint() --> solves dy/dt, y0 --> initial condition, t --> time points

### fast fourier transform (scipy.fftpack)
for frequency analysis of signals

In [349]:
from scipy import fftpack # import fft module

In [350]:
# sample signal
time_step = 0.02
time_vec = np.arange(0, 2, time_step)

signal = np.sin(2 * np.pi * 5 * time_vec)
# sine wave of frequency 5 hz
# this is the time-domain signal

In [351]:
sig_fft = fftpack.fft(signal)
# fft() --> converts signal from time domain to frequency domain

In [352]:
freq = fftpack.fftfreq(len(signal), d = time_step)
# fftfreq() --> frequency values corresponding to fft

In [353]:
fftpack.ifft(sig_fft)
# ifft() --> converts back to time domain

array([ 1.26217745e-31+0.00000000e+00j,  5.87785252e-01+0.00000000e+00j,
        9.51056516e-01+9.46633086e-32j,  9.51056516e-01+1.89326617e-31j,
        5.87785252e-01-3.15544362e-32j,  1.57150938e-16+8.35293082e-17j,
       -5.87785252e-01-5.86268954e-32j, -9.51056516e-01-4.17646541e-17j,
       -9.51056516e-01-5.91645679e-32j, -5.87785252e-01-1.35153260e-16j,
       -1.92678075e-16-4.60795672e-31j,  5.87785252e-01+6.75766299e-17j,
        9.51056516e-01-3.15544362e-32j,  9.51056516e-01+1.35153260e-16j,
        5.87785252e-01+6.98084289e-33j,  4.76895169e-16-6.75766299e-17j,
       -5.87785252e-01+3.15544362e-32j, -9.51056516e-01-8.35293082e-17j,
       -9.51056516e-01+6.27910085e-32j, -5.87785252e-01+4.17646541e-17j,
       -4.89858720e-16+0.00000000e+00j,  5.87785252e-01-1.29830626e-31j,
        9.51056516e-01-4.72676449e-32j,  9.51056516e-01-5.22817804e-32j,
        5.87785252e-01+9.26325918e-32j,  6.47009658e-16+8.35293082e-17j,
       -5.87785252e-01-4.21201781e-32j, -9.51056516

### signal processing (scipy.signal)
for filtering, resampling, detrending

In [354]:
from scipy import signal

In [355]:
# sample signal
x = np.linspace(0, 10, 100) # 100 points
y = np.sin(x) # sine signal

In [356]:
# resampling
signal.resample(y, 50)
# resample() --> changes number of samples

array([-0.12556444,  0.23717002,  0.37319429,  0.58275083,  0.71355551,
        0.85395608,  0.93090655,  0.99202185,  0.99562205,  0.97216995,
        0.89869756,  0.79671602,  0.65633556,  0.4934896 ,  0.30788636,
        0.11107116, -0.09033235, -0.2891244 , -0.47404642, -0.64277639,
       -0.78134966, -0.89303511, -0.96265976, -0.99968699, -0.98869512,
       -0.94563696, -0.85518511, -0.73966585, -0.58355387, -0.41502012,
       -0.21746644, -0.02406161,  0.18420716,  0.37016009,  0.55687783,
        0.70405448,  0.84064723,  0.92371978,  0.98996857,  0.99360286,
        0.98101052,  0.90218169,  0.81556134,  0.66371376,  0.52092371,
        0.31560533,  0.14618884, -0.08913292, -0.24153796, -0.50577781])

In [357]:
# detrending
signal.detrend(y)
# detrend() --> removes linear trend

array([-0.26570324, -0.16311714, -0.06155902,  0.0379536 ,  0.13442409,
        0.2268868 ,  0.31441694,  0.39614003,  0.47124075,  0.53897133,
        0.59865911,  0.64971343,  0.69163163,  0.72400421,  0.74651896,
        0.75896417,  0.76123079,  0.75331354,  0.73531093,  0.70742431,
        0.66995578,  0.62330513,  0.56796575,  0.5045196 ,  0.4336313 ,
        0.35604131,  0.27255845,  0.18405158,  0.09144078, -0.00431201,
       -0.10221284, -0.20124586, -0.30038367, -0.39859781, -0.49486922,
       -0.58819868, -0.67761692, -0.76219457, -0.84105159, -0.91336627,
       -0.9783836 , -1.03542293, -1.08388499, -1.12325791, -1.15312249,
       -1.17315647, -1.1831378 , -1.1829469 , -1.17256791, -1.15208881,
       -1.12170056, -1.08169514, -1.03246256, -0.97448689, -0.90834135,
       -0.83468243, -0.75424322, -0.66782593, -0.57629371, -0.48056186,
       -0.38158849, -0.28036476, -0.17790476, -0.07523518,  0.02661513,
        0.12662569,  0.22379478,  0.31714964,  0.40575638,  0.48

### image manipulation (scipy.ndimage)
for image transformations and filtering

In [358]:
from scipy import ndimage

In [359]:
face = np.random.rand(200, 200)
# creates a dummy image (2D array)
# values between 0 and 1

In [360]:
# shift
ndimage.shift(face, (50, 50))
# moves image in x and y direction

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.3721595 , 0.90608826,
        0.84005513],
       [0.        , 0.        , 0.        , ..., 0.82755464, 0.46952563,
        0.36265573],
       [0.        , 0.        , 0.        , ..., 0.03915762, 0.96671593,
        0.23142498]])

In [361]:
# rotated
ndimage.rotate(face, 30)
# rotates image by 30 degrees

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [362]:
# zoom
ndimage.zoom(face, 2)
# zoom() --> scales image

array([[ 0.04502241, -0.00149856,  0.09503364, ...,  0.40689053,
         0.28209789,  0.26021011],
       [ 0.40998393,  0.33131988,  0.27611499, ...,  0.55800285,
         0.37919369,  0.25006406],
       [ 0.91717193,  0.78105377,  0.49866126, ...,  0.83861197,
         0.5973887 ,  0.34267736],
       ...,
       [ 0.46443283,  0.43942999,  0.46713511, ...,  0.81077652,
         0.4784442 ,  0.21263323],
       [ 0.52360681,  0.39798743,  0.3389697 , ...,  0.87472797,
         0.50365979,  0.21350723],
       [ 0.63207139,  0.4177712 ,  0.25116826, ...,  0.92266341,
         0.53372221,  0.23036198]])

reference: *[scipy-lectures.org](http://scipy-lectures.org/intro/scipy.html)*